<?php
// SEO in Theme Settings
    acf_add_local_field_group(array (
	'key' => 'group_56ced5baec41e',
	'title' => 'SEO',
	'fields' => array (
		array (
			'key' => 'field_56ced61ae9ee8',
			'label' => 'Meta Keywords',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56ced5c1e9ee7',
			'label' => 'Meta Keywords (für alle Seiten) (deutsch)',
			'name' => 'meta_keywords_de',
			'type' => 'textarea',
			'instructions' => 'Hier könnt Ihr die Stichwörter für die Google-Suche eingeben',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5704e4a7456a4',
			'label' => 'Meta Keywords (für alle Seiten) (englisch)',
			'name' => 'meta_keywords_en',
			'type' => 'textarea',
			'instructions' => 'Hier könnt Ihr die Stichwörter für die Google-Suche eingeben',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5704e4cc456a5',
			'label' => 'Meta Keywords (für alle Seiten) (chinesisch)',
			'name' => 'meta_keywords_zn',
			'type' => 'textarea',
			'instructions' => 'Hier könnt Ihr die Stichwörter für die Google-Suche eingeben',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56ced6483007a',
			'label' => 'Meta Description',
			'name' => '_kopieren',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56ced6573007b',
			'label' => 'Meta Description (für alle Seiten) (deutsch)',
			'name' => 'meta_description_de',
			'type' => 'textarea',
			'instructions' => 'Hier könnt Ihr eine Seitenbeschreibung für Google eingeben.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5704e4fe2d0b2',
			'label' => 'Meta Description (für alle Seiten) (englisch)',
			'name' => 'meta_description_en',
			'type' => 'textarea',
			'instructions' => 'Hier könnt Ihr eine Seitenbeschreibung für Google eingeben.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5704e5122d0b3',
			'label' => 'Meta Description (für alle Seiten) (chinesisch)',
			'name' => 'meta_description_zn',
			'type' => 'textarea',
			'instructions' => 'Hier könnt Ihr eine Seitenbeschreibung für Google eingeben.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56d75899f4a58',
			'label' => 'Analytics Code',
			'name' => '_kopieren',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56d758ba1d2d4',
			'label' => 'Analytics',
			'name' => 'analytics',
			'type' => 'textarea',
			'instructions' => 'Falls Ihr habt, den Analytics/Tracking Code (z.B. Google, Piwik) eintragen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 100,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
?>